(def n (read))
(cond
    (= n 1) (println "January")
    (= n 2) (println "February")
    (= n 3) (println "March")
    (= n 4) (println "April")
    (= n 5) (println "May")
    (= n 6) (println "June")
    (= n 7) (println "July")
    (= n 8) (println "August")
    (= n 9) (println "September")
    (= n 10) (println "October")
    (= n 11) (println "November")
    (= n 12) (println "December")
    :else (println ""))
