(def a (read))
(def b (read))
(def c (read))
(def d (sort >[a b c]))
(def a (nth d 0))
(def b (nth d 1))
(def c (nth d 2))

(if (>= a (+ b c))
    (println "NAO FORMA TRIANGULO") 
)
(if (== (* a a) (+ (* b b) (* c c)))
    (println "TRIANGULO RETANGULO")      
)
(if (and (> (* a a) (+ (* b b) (* c c))) (< a (+ b c)))
    (println "TRIANGULO OBTUSANGULO")      
)
(if (< (* a a) (+ (* b b) (* c c)))
    (println "TRIANGULO ACUTANGULO")      
)
(if (== a b c)
    (println "TRIANGULO EQUILATERO")   
)
(if (or (and (== a b) (not= a c)) (and (== a c) (not= a b)) (and (== b c) (not= b a)))
    (println "TRIANGULO ISOSCELES")
)